en:
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/dotkaio/imagepulate/blob/master/docs/PROMPT_GUIDE.md).
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Frame Index: Frame Index
  Preview: Preview
  Model: Model
  Pixelize: Pixelize
  Solid Color: Solid Color
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Filter Modes: Filter Modes
  Pixel Size: Pixel Size
  Video File Format: Video File Format
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Video Segmentation: Video Segmentation
  Input image here: Input image here
  Automatic Segmentation: Automatic Segmentation
  Box Prompt: Box Prompt
  Image Input Mode: Image Input Mode
  multimask_output: multimask_output
  Mask Parameters: Mask Parameters
  GENERATE PSD: GENERATE PSD
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Layer Divider: Layer Divider
ko:
  If you don't know how to prompt: í”„ë¡¬í”„íŠ¸ë¥¼ ì–´ë–»ê²Œ ë„£ëŠ”ì§€ ëª¨ë¥´ì‹ ë‹¤ë©´, [PROMPT_GUIDE.md](https://github.com/dotkaio/imagepulate/blob/master/docs/PROMPT_GUIDE.md)ë¥¼
    ë´ì£¼ì„¸ìš”.
  Upload Input Video: ì˜ìƒì„ ì—…ë¡œë“œ í•˜ì„¸ìš”
  Prompt image with Box & Point: í”„ë¡¬í”„íŠ¸ (ë°•ìŠ¤ & í¬ì¸íŠ¸)
  Frame Index: ë™ì˜ìƒ í”„ë ˆì„ ìˆ˜
  Preview: í”„ë¦¬ë·°
  Model: ëª¨ë¸
  Pixelize: ëª¨ìì´í¬
  Solid Color: ë‹¨ìƒ‰ (ë°°ê²½ ì œê±°ìš©)
  Transparent Color (Background Remover): íˆ¬ëª…ìƒ‰ (ë°°ê²½ ì œê±°ìš©)
  Filter Modes: í•„í„° ëª¨ë“œ
  Pixel Size: ëª¨ìì´í¬ í”½ì…€ í¬ê¸°
  Video File Format: ì˜ìƒ íŒŒì¼ í˜•ì‹
  invert mask: ë¶„í•  ì˜ì—­ ë°˜ì „
  GENERATE PREVIEW: í”„ë¦¬ë·° ìƒì„±
  GENERATE VIDEO: ì˜ìƒ ìƒì„±
  Output Video: ì˜ìƒ ê²°ê³¼ë¬¼
  Downloadable Output File: ì˜ìƒ íŒŒì¼
  ğŸ“ Open Output folder: ğŸ“ ì¶œë ¥ í´ë” ì—´ê¸°
  Video Segmentation: ì˜ìƒ ë¶„í• 
  Input image here: Input image here
  Automatic Segmentation: ìë™ ë¶„í• 
  Box Prompt: ë°•ìŠ¤ í”„ë¡¬í”„íŠ¸
  Image Input Mode: í”„ë¡¬í”„íŠ¸ ëª¨ë“œ
  multimask_output: multimask_output
  Mask Parameters: Mask Parameters
  GENERATE PSD: PSD íŒŒì¼ ìƒì„±
  Output images will be shown here: ë¶„í• ëœ ì´ë¯¸ì§€ë“¤
  Generated psd file: ìƒì„±ëœ psd íŒŒì¼
  ğŸ“ Open PSD folder: ğŸ“ PSD ì¶œë ¥ í´ë” ì—´ê¸°
  Layer Divider: ë ˆì´ì–´ ë¶„ë¦¬ê¸°
ja:
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/dotkaio/imagepulate/blob/master/docs/PROMPT_GUIDE.md).
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Frame Index: Frame Index
  Preview: Preview
  Model: Model
  Pixelize: Pixelize
  Solid Color: Solid Color
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Filter Modes: Filter Modes
  Pixel Size: Pixel Size
  Video File Format: Video File Format
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Video Segmentation: Video Segmentation
  Input image here: Input image here
  Automatic Segmentation: Automatic Segmentation
  Box Prompt: Box Prompt
  Image Input Mode: Image Input Mode
  multimask_output: multimask_output
  Mask Parameters: Mask Parameters
  GENERATE PSD: GENERATE PSD
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Layer Divider: Layer Divider
es:
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/dotkaio/imagepulate/blob/master/docs/PROMPT_GUIDE.md).
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Frame Index: Frame Index
  Preview: Preview
  Model: Model
  Pixelize: Pixelize
  Solid Color: Solid Color
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Filter Modes: Filter Modes
  Pixel Size: Pixel Size
  Video File Format: Video File Format
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Video Segmentation: Video Segmentation
  Input image here: Input image here
  Automatic Segmentation: Automatic Segmentation
  Box Prompt: Box Prompt
  Image Input Mode: Image Input Mode
  multimask_output: multimask_output
  Mask Parameters: Mask Parameters
  GENERATE PSD: GENERATE PSD
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Layer Divider: Layer Divider
fr:
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/dotkaio/imagepulate/blob/master/docs/PROMPT_GUIDE.md).
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Frame Index: Frame Index
  Preview: Preview
  Model: Model
  Pixelize: Pixelize
  Solid Color: Solid Color
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Filter Modes: Filter Modes
  Pixel Size: Pixel Size
  Video File Format: Video File Format
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Video Segmentation: Video Segmentation
  Input image here: Input image here
  Automatic Segmentation: Automatic Segmentation
  Box Prompt: Box Prompt
  Image Input Mode: Image Input Mode
  multimask_output: multimask_output
  Mask Parameters: Mask Parameters
  GENERATE PSD: GENERATE PSD
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Layer Divider: Layer Divider
de:
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/dotkaio/imagepulate/blob/master/docs/PROMPT_GUIDE.md).
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Frame Index: Frame Index
  Preview: Preview
  Model: Model
  Pixelize: Pixelize
  Solid Color: Solid Color
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Filter Modes: Filter Modes
  Pixel Size: Pixel Size
  Video File Format: Video File Format
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Video Segmentation: Video Segmentation
  Input image here: Input image here
  Automatic Segmentation: Automatic Segmentation
  Box Prompt: Box Prompt
  Image Input Mode: Image Input Mode
  multimask_output: multimask_output
  Mask Parameters: Mask Parameters
  GENERATE PSD: GENERATE PSD
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Layer Divider: Layer Divider
zh:
  If you don't know how to prompt: If you don't know how to prompt, see [PROMPT_GUIDE.md](https://github.com/dotkaio/imagepulate/blob/master/docs/PROMPT_GUIDE.md).
  Upload Input Video: Upload Input Video
  Prompt image with Box & Point: Prompt image with Box & Point
  Frame Index: Frame Index
  Preview: Preview
  Model: Model
  Pixelize: Pixelize
  Solid Color: Solid Color
  Transparent Color (Background Remover): Transparent Color (Background Remover)
  Filter Modes: Filter Modes
  Pixel Size: Pixel Size
  Video File Format: Video File Format
  invert mask: invert mask
  GENERATE PREVIEW: GENERATE PREVIEW
  GENERATE VIDEO: GENERATE VIDEO
  Output Video: Output Video
  Downloadable Output File: Downloadable Output File
  ğŸ“ Open Output folder: ğŸ“ Open Output folder
  Video Segmentation: Video Segmentation
  Input image here: Input image here
  Automatic Segmentation: Automatic Segmentation
  Box Prompt: Box Prompt
  Image Input Mode: Image Input Mode
  multimask_output: multimask_output
  Mask Parameters: Mask Parameters
  GENERATE PSD: GENERATE PSD
  Output images will be shown here: Output images will be shown here
  Generated psd file: Generated psd file
  ğŸ“ Open PSD folder: ğŸ“ Open PSD folder
  Layer Divider: Layer Divider
